services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  LMS3\Docuseal\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  connection.docuseal:
    class: 'TYPO3\CMS\Core\Database\Connection'
    factory:
      - '@TYPO3\CMS\Core\Database\ConnectionPool'
      - 'getConnectionForTable'
    arguments:
      - 'tx_docuseal_domain_model_signatures'

  LMS3\Docuseal\Service\SignatureService:
    arguments:
      $connection: '@connection.docuseal'
